apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: new-end-point
  name: new-end-point
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-end-point
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: new-end-point
    spec:
      containers:
      - image: helunxing/new-end-point-server:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: new-end-point-rest-api-server
        env:
          - name: HELLO_URI
            value: http://hello-world
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-end-point
  name: new-end-point
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: new-end-point
  sessionAffinity: None
  type: LoadBalancer
