### should be 201
PUT localhost:8200/joinInfo
Content-Type: application/json

{
  "userId": "1",
  "eventId": "1",
  "optionsStr": "options from req.http"
}

> {%
    client.global.set ("join_addr", response.headers.valueOf("location"));
%}

### should be 200
GET {{join_addr}}

### should be 201
PUT localhost:8200/joinInfo
Content-Type: application/json

{
  "userId": "1",
  "eventId": "1",
  "optionsStr":"options from req.http changed"
}

### should be 200
GET {{join_addr}}

### should be 200
DELETE {{join_addr}}
