### get demo
GET http://localhost:8080/books

### delete demo
DELETE http://localhost:8080/books/0

### post demo
POST http://localhost:8080/books
Content-Type: application/json

{
  "time_options": "fege",
  "title": "2fwefw"
}

### get demo
GET http://localhost:8080/books
