### should be 404
GET http://localhost:8100/users

###
GET http://localhost:8100/user/sub/subfromDefault_Data

### should be 201
GET http://localhost:8100/user/sub/testsubfrom_unittest

> {%
    client.global.set("user_addr", response.headers.valueOf("location"));
%}

### should be 200, and data same with above
GET {{user_addr}}

### should be 404
GET http://localhost:8100/user/15990

### should be 201
PUT {{user_addr}}

{
  "subId": "subIdunittestUpdated",
  "loginKey": "keyunittestUpdated"
}

### should be 404
PUT http://localhost:8100/user/15990

{
  "subId": "subIdUpdated",
  "loginKey": "keyUpdated"
}

### should be 200, and data same with above
GET {{user_addr}}

### should be 200
DELETE {{user_addr}}

### should be 404
GET {{user_addr}}
